#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
#  nupdf.py
#
#  Copyright 2013 Oz Nahum <nahumoz@gmail.com>
#
#  This program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 2 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program; if not, write to the Free Software
#  Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
#  MA 02110-1301, USA.
#
#  This file is part of nupdf
#  https://github.com/nutoo/nupdf

import sys
import os

from nupdf.nupdf import Poprender

if __name__ == '__main__':
    try:
        if len(sys.argv) == 2:
            pop = Poprender()
            pop.main()
        else:
            print "Usage:"
            print os.path.basename(sys.argv[0]) + " filename.pdf"
    except KeyboardInterrupt:
        __name__
